POST http://localhost:3001/app/admin
Content-Type: application/json

{
        "Username_Admin": "request.body.Username_Admin",
        "mdp":" request.body.mdp",
        "FirstName": "request.body.FirstName",
        "LastName": "request.body.LastName",
        "Cin": "request.body.Cin",
        "Phone_Number": "request.body.Phone_Number",
        "Email": "request.body.Email",
        "Occupation": "request.body.Occupation",
        "Password": "request.body.Password",
        "Nom_client": "request.body.Nom_client",
        "Marque_et_Type_du_Véhicule": "request.body.Marque_et_Type_du_Véhicule",
        "Tél_client": "request.body.Tél_client",
        "Immatriculation": "request.body.Immatriculation",
        "Proprieter_du_véhicule": "request.body.Proprieter_du_véhicule",
        "Compteur_KM_Véhicule": "request.body.Compteur_KM_Véhicule",
        "Tél_Proprieter": "request.body.Tél_Proprieter",
        "Model_du_Groupe": "request.body.Model_du_Groupe",
        "Lieu_intervention":"request.body.Lieu_intervention",
        "N_Série": "request.body.N_Série",
        "Compteur_Horaire_Groupe": "request.body.Compteur_Horaire_Groupe",
        "Descriptif_du_problème": "request.body.Descriptif_du_problème",
        "traveaux_demandé": "request.body.traveaux_demandé",
        "Observations_complémentaires": "request.body.Observations_complémentaires",
        "Garentie":"request.body.Garentie",
        "Nom_Technicien": "request.body.Nom_Technicien",
        "Diagnostique": "request.body.Diagnostique",
        "travaille_a_realisé": "request.body.travaille_a_realisé",
        "Moteur": "request.body.Moteur",
        "Compteur": "request.body.Compteur",
        "Filtre_a_eau": "request.body.Filtre_a_eau",
        "NFiltre_a_eau": 2,
        "Thermostat": "request.body.Thermostat",
        "Compressuer":" request.body.Compressuer",
        "Condenseur":" request.body.Condenseur",
        "NCondenseur": 2,
        "begin": "request.body.begin",
        "Terminate":" request.body.Terminate",
        "avis_Client": "request.body.avis_Client"
}